name: reproduce

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.9.3

solidity: 
  import_remapping:
    - "@openzeppelin/contracts@v4.9.3/=OpenZeppelin/4.9.3"

plugins:
  - name: solidity
  - name: foundry
  - name: ens
  - name: etherscan
  - name: alchemy

ethereum:
  default_network: mainnet-fork
  local:
    default_provider: foundry
  
foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
